---
name: "ros1-basic"
services:
  # ROS CORE
  core:
    image: robotnik/examples:noetic-basic
    build:
      context: .
      dockerfile: Dockerfile
      args:
        base_image: robotnik/ros
        ros_distro: noetic
    environment:
      ROS_MASTER_URI: http://core:11311
      ROS_HOSTNAME: core
      STARTUP_TYPE: generic
      ROS_BU_LAUNCH: "roscore"

  # TALKER NODE
  talker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        base_image: robotnik/ros
        ros_distro: noetic
    environment:
      ROS_MASTER_URI: http://core:11311
      ROS_HOSTNAME: talker
      ROS_BU_PKG: "roscpp_tutorials"
      ROS_BU_LAUNCH: "talker"
      CHECK_NODES: "true"
      NODES_TO_CHECK: "/rosout"
      HEALTHCHECK_NODES: "/talker"
    tty: true

  # LISTENER NODE
  listener:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        base_image: robotnik/ros
        ros_distro: noetic
    environment:
      ROS_MASTER_URI: http://core:11311
      ROS_HOSTNAME: listener
      ROS_BU_PKG: "roscpp_tutorials"
      ROS_BU_LAUNCH: "listener"
      CHECK_NODES: "true"
      NODES_TO_CHECK: "/rosout /talker"
      HEALTHCHECK_NODES: "/listener"
    tty: true
